#! /usr/bin/env bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

packages=(
  bat # cat alternative
  build-essential
  shellcheck # used for checking shell scripts, used by shellcheck vscode extension
  silversearcher-ag # Just a fast awk alternative
)

apt install "${packages[@]}"
