#! /usr/bin/env bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
add-apt-repository ppa:mmstick76/alacritty
apt update

packages=(
  autoconf automake pkg-config libevent-dev libncurses-dev # for building tmux
  bat # cat alternative
  build-essential
  shellcheck # used for checking shell scripts, used by shellcheck vscode extension
  silversearcher-ag # Just a fast awk alternative
  libinput-tools xdotool wmctrl # for libinput gestures
  alacritty
)

apt install "${packages[@]}"
