#! /usr/bin/env bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

add-apt-repository -n ppa:mmstick76/alacritty
add-apt-repository -n ppa:jonaski/strawberry

apt update

packages=(
  autoconf automake pkg-config libevent-dev libncurses-dev # for building tmux
  bat # cat alternative
  build-essential
  shellcheck # used for checking shell scripts, used by shellcheck vscode extension
  silversearcher-ag # Just a fast awk alternative
  libinput-tools xdotool wmctrl # for libinput gestures
  alacritty
  flameshot # screenshot
  peek # gif screen recorder
  strawberry # music player
)

apt install "${packages[@]}"

cat <<- END
Other apps
 * https://github.com/johnfactotum/foliate/ # ebook reader
 * https://github.com/dandavison/delta/releases # fancy git
END
