#! /usr/bin/env zsh

# zmodload zsh/zprof # must be at the start of file
# Path to your oh-my-zsh installation.

# http://www.refining-linux.org/archives/49/ZSH-Gem-15-Shared-history/
# instant append to history
setopt inc_append_history
# share history between sessions
setopt share_history
setopt hist_ignore_all_dups

disable r

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# No theme!
ZSH_THEME=""

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  colorize
  extract
  npm
  fzf
  rustup
  tmuxinator
  # docker docker-compose
)

ZSH_ROOT="$DOTFILES_ROOT/zsh"

source "$ZSH_ROOT/aliases.zsh"
source "$ZSH_ROOT/exports.zsh"
source "$ZSH_ROOT/configs.zsh"

# I store configuration that is private here, not included in the repository
if [[ -d $DOTFILES_ROOT/my ]]; then
  for file in $DOTFILES_ROOT/my/*.zsh; do
    source "$file"
  done
fi

source "$ZSH_ROOT/plugins.zsh"
source "$ZSH/oh-my-zsh.sh"
source "$ZSH_ROOT/theme.zsh"


zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'

source "$ZSH_ROOT/functions.zsh"

# autoload -U compinit && compinit

export PATH=$HOME/.local/bin/:$PATH

# zprof # Must be end of file
