# Path to your oh-my-zsh installation.
export ZSH=/Users/kito/.oh-my-zsh

local P_ROOT=~/.kito/plugins

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# No theme!
ZSH_THEME=""

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  brew-cask colorize extract
)

# Load completions and don't pollute aliases!
completion_plugins=(
  # These are already handled
  # rails gem thor brew
)

for plugin ($completion_plugins); do
  fpath=($ZSH/plugins/$plugin $fpath)
done

function load () {
  for script in "$@"
  do
    source ~/.kito/$script.zsh
  done
}

load zsh rbenv exports aliases docker

if [[ -d ~/.kito/my ]]; then
  for file in ~/.kito/my/*.zsh; do
    source $file
  done
fi

[ -d $P_ROOT/zsh-completions ] && fpath+=$P_ROOT/zsh-completions/src

source $ZSH/oh-my-zsh.sh

[ -f $P_ROOT/fzf.zsh ] && source $P_ROOT/fzf.zsh

[ -f $P_ROOT/bookmark.zsh ] && source $P_ROOT/bookmark.zsh

[ -f $P_ROOT/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
source $P_ROOT/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source ~/.kito/k-theme.zsh

zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}'

load functions

unset -f load

source ~/.kito/my/npm_completion.sh
